### ISSUE TITLE
Add More APIs

### ISSUE THREAD

**Issue by DeveloperAspire** [kaf-lamed-beyt/ng-apis#3]
The current list of APIS doesn't cover much, I want to add more. 

@kaf-lamed-beyt Assign this to me. I already have a list.

**Comment by kaf-lamed-beyt** [comment]
Assigning you right away!!! 🚀🚀

**Comment by DeveloperAspire** [comment]
I am picking this up now. So I don't forget them.

**Comment by kaf-lamed-beyt** [comment]
Thanks again @DeveloperAspire! ✨️

Have you been able to assign me to the Next.js template issue?

**Comment by kaf-lamed-beyt** [comment]
#6 fixes this

**Comment by DeveloperAspire** [comment]
@kaf-lamed-beyt Anytime boss man. Apart from this, I want to contribute to more tools and OSS projects, if you have more, please plug me in 🙏 I am very much passionate about this.

I haven’t been able to assign you yet. I have tried it is not working. I shared a picture on Twitter

**Comment by kaf-lamed-beyt** [comment]
> I haven’t been able to assign you yet. I have tried it is not working. I shared a picture on Twitter

Oh! I'll take a look at it now.

**Comment by kaf-lamed-beyt** [comment]
> @kaf-lamed-beyt Anytime boss man. Apart from this, I want to contribute to more tools and OSS projects, if you have more, please plug me in 🙏 I am very much passionate about this.

...about this, I have one pending project, somewhere. When I'm done with some of my tasks at hand, I'll circle back to this comment, so we can have a chat.

And about the issue of assigning me, I think it may be because I haven't commented on that issue, so github can be aware that I am part of that conversation, and by so doing, it can obtain my username when you try to assign me.
